In [2]:
!pip install pymongo pandas

Requirement already satisfied: pymongo in /usr/local/python/3.11.15/lib/python3.11/site-packages (4.16.0)
Requirement already satisfied: pandas in /usr/local/python/3.11.15/lib/python3.11/site-packages (3.0.1)
Requirement already satisfied: dnspython<3.0.0,>=2.6.1 in /usr/local/python/3.11.15/lib/python3.11/site-packages (from pymongo) (2.8.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.11.15/lib/python3.11/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/python/3.11.15/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/python/3.11.15/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
from pymongo import MongoClient
import pandas as pd
from datetime import datetime

In [4]:
client = MongoClient("mongodb://root:rootpass@localhost:27017")
print(client.server_info()["version"])

8.2.6

In [5]:
db = client['loja']
colecao = db['vendas']

In [6]:
dados = [
    {
        "cliente": "Ana",
        "produto": "Mouse",
        "categoria": "Informática",
        "quantidade": 2,
        "preco_unitario": 50,
        "cidade": "Ourinhos",
        "data": datetime(2026, 3, 1),
        "forma_pagamento": "Cartão"
    },
    {
        "cliente": "Bruno",
        "produto": "Teclado",
        "categoria": "Informática",
        "quantidade": 1,
        "preco_unitario": 120,
        "cidade": "Jacarezinho",
        "data": datetime(2026, 3, 2),
        "forma_pagamento": "Pix"
    },
    {
        "cliente": "Carla",
        "produto": "Caderno",
        "categoria": "Papelaria",
        "quantidade": 5,
        "preco_unitario": 15,
        "cidade": "Ourinhos",
        "data": datetime(2026, 3, 2),
        "forma_pagamento": "Dinheiro"
    },
    {
        "cliente": "Daniel",
        "produto": "Caneta",
        "categoria": "Papelaria",
        "quantidade": 10,
        "preco_unitario": 3,
        "cidade": "Salto Grande",
        "data": datetime(2026, 3, 3),
        "forma_pagamento": "Pix"
    },
    {
        "cliente": "Elaine",
        "produto": "Monitor",
        "categoria": "Informática",
        "quantidade": 1,
        "preco_unitario": 900,
        "cidade": "Ourinhos",
        "data": datetime(2026, 3, 3),
        "forma_pagamento": "Cartão"
    },
    {
        "cliente": "Fabio",
        "produto": "Mochila",
        "categoria": "Acessórios",
        "quantidade": 2,
        "preco_unitario": 80,
        "cidade": "Jacarezinho",
        "data": datetime(2026, 3, 4),
        "forma_pagamento": "Boleto"
    },
    {
        "cliente": "Gabriela",
        "produto": "Livro",
        "categoria": "Livros",
        "quantidade": 3,
        "preco_unitario": 40,
        "cidade": "Ourinhos",
        "data": datetime(2026, 3, 4),
        "forma_pagamento": "Pix"
    },
    {
        "cliente": "Henrique",
        "produto": "Fone",
        "categoria": "Informática",
        "quantidade": 2,
        "preco_unitario": 150,
        "cidade": "Assis",
        "data": datetime(2026, 3, 5),
        "forma_pagamento": "Cartão"
    },
    {
        "cliente": "Isabela",
        "produto": "Agenda",
        "categoria": "Papelaria",
        "quantidade": 4,
        "preco_unitario": 20,
        "cidade": "Salto Grande",
        "data": datetime(2026, 3, 5),
        "forma_pagamento": "Dinheiro"
    },
    {
        "cliente": "João",
        "produto": "Webcam",
        "categoria": "Informática",
        "quantidade": 1,
        "preco_unitario": 250,
        "cidade": "Ourinhos",
        "data": datetime(2026, 3, 6),
        "forma_pagamento": "Pix"
    }
]

In [7]:
colecao.insert_many(dados)

InsertManyResult([ObjectId('69bc9c11a74d609d3dce4cd1'), ObjectId('69bc9c11a74d609d3dce4cd2'), ObjectId('69bc9c11a74d609d3dce4cd3'), ObjectId('69bc9c11a74d609d3dce4cd4'), ObjectId('69bc9c11a74d609d3dce4cd5'), ObjectId('69bc9c11a74d609d3dce4cd6'), ObjectId('69bc9c11a74d609d3dce4cd7'), ObjectId('69bc9c11a74d609d3dce4cd8'), ObjectId('69bc9c11a74d609d3dce4cd9'), ObjectId('69bc9c11a74d609d3dce4cda')], acknowledged=True)

In [8]:
dados_mongo = list(colecao.find({
    "preco_unitario": {"$gte" : 100, "$lte" : 300}
}))

display(dados_mongo)

[{'_id': ObjectId('69bc991226365d4e7c25becc'),
  'cliente': 'Bruno',
  'produto': 'Teclado',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 120,
  'cidade': 'Jacarezinho',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69bc991226365d4e7c25bed2'),
  'cliente': 'Henrique',
  'produto': 'Fone',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 150,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69bc991226365d4e7c25bed4'),
  'cliente': 'João',
  'produto': 'Webcam',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 250,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69bc9c11a74d609d3dce4cd2'),
  'cliente': 'Bruno',
  'produto': 'Teclado',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 120,
  'cidade': 'Jacarezinho',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69bc9c11a74d609d3dce4cd8'),
  'cliente': 'Henrique',
  'produto': 'Fone',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 150,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69bc9c11a74d609d3dce4cda'),
  'cliente': 'João',
  'produto': 'Webcam',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 250,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'}]

In [9]:
dados_mongo = list(colecao.find({
    "cidade": {"$in" : ['Ourinhos', 'Assis']}
}))

display(dados_mongo)

[{'_id': ObjectId('69bc991226365d4e7c25becb'),
  'cliente': 'Ana',
  'produto': 'Mouse',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 50,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69bc991226365d4e7c25becd'),
  'cliente': 'Carla',
  'produto': 'Caderno',
  'categoria': 'Papelaria',
  'quantidade': 5,
  'preco_unitario': 15,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69bc991226365d4e7c25becf'),
  'cliente': 'Elaine',
  'produto': 'Monitor',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 900,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69bc991226365d4e7c25bed1'),
  'cliente': 'Gabriela',
  'produto': 'Livro',
  'categoria': 'Livros',
  'quantidade': 3,
  'preco_unitario': 40,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69bc991226365d4e7c25bed2'),
  'cliente': 'Henrique',
  'produto': 'Fone',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 150,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69bc991226365d4e7c25bed4'),
  'cliente': 'João',
  'produto': 'Webcam',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 250,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69bc9c11a74d609d3dce4cd1'),
  'cliente': 'Ana',
  'produto': 'Mouse',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 50,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69bc9c11a74d609d3dce4cd3'),
  'cliente': 'Carla',
  'produto': 'Caderno',
  'categoria': 'Papelaria',
  'quantidade': 5,
  'preco_unitario': 15,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69bc9c11a74d609d3dce4cd5'),
  'cliente': 'Elaine',
  'produto': 'Monitor',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 900,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69bc9c11a74d609d3dce4cd7'),
  'cliente': 'Gabriela',
  'produto': 'Livro',
  'categoria': 'Livros',
  'quantidade': 3,
  'preco_unitario': 40,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69bc9c11a74d609d3dce4cd8'),
  'cliente': 'Henrique',
  'produto': 'Fone',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 150,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69bc9c11a74d609d3dce4cda'),
  'cliente': 'João',
  'produto': 'Webcam',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 250,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'}]

In [12]:
df = pd.DataFrame(dados_mongo)
df

,_id,cliente,produto,categoria,quantidade,preco_unitario,cidade,data,forma_pagamento
0,69bc991226365d4e7c25becb,Ana,Mouse,Informática,2,50,Ourinhos,2026-03-01,Cartão
1,69bc991226365d4e7c25becd,Carla,Caderno,Papelaria,5,15,Ourinhos,2026-03-02,Dinheiro
2,69bc991226365d4e7c25becf,Elaine,Monitor,Informática,1,900,Ourinhos,2026-03-03,Cartão
3,69bc991226365d4e7c25bed1,Gabriela,Livro,Livros,3,40,Ourinhos,2026-03-04,Pix
4,69bc991226365d4e7c25bed2,Henrique,Fone,Informática,2,150,Assis,2026-03-05,Cartão
5,69bc991226365d4e7c25bed4,João,Webcam,Informática,1,250,Ourinhos,2026-03-06,Pix
6,69bc9c11a74d609d3dce4cd1,Ana,Mouse,Informática,2,50,Ourinhos,2026-03-01,Cartão
7,69bc9c11a74d609d3dce4cd3,Carla,Caderno,Papelaria,5,15,Ourinhos,2026-03-02,Dinheiro
8,69bc9c11a74d609d3dce4cd5,Elaine,Monitor,Informática,1,900,Ourinhos,2026-03-03,Cartão
9,69bc9c11a74d609d3dce4cd7,Gabriela,Livro,Livros,3,40,Ourinhos,2026-03-04,Pix
10,69bc9c11a74d609d3dce4cd8,Henrique,Fone,Informática,2,150,Assis,2026-03-05,Cartão
11,69bc9c11a74d609d3dce4cda,João,Webcam,Informática,1,250,Ourinhos,2026-03-06,Pix

In [13]:
df.isnull().sum()

_id                0
cliente            0
produto            0
categoria          0
quantidade         0
preco_unitario     0
cidade             0
data               0
forma_pagamento    0
dtype: int64

In [16]:
df['valor_total'] = df['quantidade'] * df['preco_unitario']
df.head(5)

,_id,cliente,produto,categoria,quantidade,preco_unitario,cidade,data,forma_pagamento,valor_total
0,69bc991226365d4e7c25becb,Ana,Mouse,Informática,2,50,Ourinhos,2026-03-01,Cartão,100
1,69bc991226365d4e7c25becd,Carla,Caderno,Papelaria,5,15,Ourinhos,2026-03-02,Dinheiro,75
2,69bc991226365d4e7c25becf,Elaine,Monitor,Informática,1,900,Ourinhos,2026-03-03,Cartão,900
3,69bc991226365d4e7c25bed1,Gabriela,Livro,Livros,3,40,Ourinhos,2026-03-04,Pix,120
4,69bc991226365d4e7c25bed2,Henrique,Fone,Informática,2,150,Assis,2026-03-05,Cartão,300

In [17]:
faturamento = df['valor_total'].sum()
print("Faturamento Total: ", faturamento)

Faturamento Total:  3490

In [18]:
faturamento_categoria = df.groupby('categoria')['valor_total'].sum().sort_values(ascending=False)
faturamento_categoria

categoria
Informática    3100
Livros          240
Papelaria       150
Name: valor_total, dtype: int64

In [20]:
faturamento_produto = df.groupby('produto')['valor_total'].sum().sort_values(ascending=False)
faturamento_produto

produto
Monitor    1800
Fone        600
Webcam      500
Livro       240
Mouse       200
Caderno     150
Name: valor_total, dtype: int64

In [21]:
vendas_por_cidade = df['cidade'].value_counts()
vendas_por_cidade

cidade
Ourinhos    10
Assis        2
Name: count, dtype: int64

In [24]:
media_valor_vendas = df['valor_total'].mean()
print(f"Média do valor das vendas: {media_valor_vendas:.2f}")

Média do valor das vendas: 290.83

In [25]:
produto_top = df.groupby("produto")['valor_total'].sum().idxmax()
produto_top

'Monitor'

In [29]:
cidade_top = df["cidade"].value_counts().idxmax()
cidade_top

'Ourinhos'

In [33]:
relatorio = {
    "data_geracao" : datetime.now(),
    "faturamento_total": float(faturamento),
    "faturamento_categoria" : faturamento_categoria.to_dict(),
    "produto_top" : produto_top,
    "cidade_top": cidade_top 
}

display(relatorio)

{'data_geracao': datetime.datetime(2026, 3, 20, 1, 30, 57, 549704),
 'faturamento_total': 3490.0,
 'faturamento_categoria': {'Informática': 3100,
  'Livros': 240,
  'Papelaria': 150},
 'produto_top': 'Monitor',
 'cidade_top': 'Ourinhos'}

In [34]:
colecao_relatorios = db['relatorios']
colecao_relatorios.insert_one(relatorio)

InsertOneResult(ObjectId('69bca354a74d609d3dce4cdc'), acknowledged=True)

In [36]:
for r in colecao_relatorios.find():
    display(r)

{'_id': ObjectId('69bca354a74d609d3dce4cdc'),
 'data_geracao': datetime.datetime(2026, 3, 20, 1, 30, 57, 549000),
 'faturamento_total': 3490.0,
 'faturamento_categoria': {'Informática': 3100,
  'Livros': 240,
  'Papelaria': 150},
 'produto_top': 'Monitor',
 'cidade_top': 'Ourinhos'}